from setuptools import setup, find_packages

setup(
  name = 'ne01-wholebody-v4-retargeting',
  packages = find_packages(),
  author="Yanjie Ze",
  author_email="lastyanjieze@gmail.com",
  description="NE01 WholeBody V4 motion retargeting",
  long_description=open("README.md").read(),
  long_description_content_type="text/markdown",
  url="https://github.com/perfect668/motion-fix",
  license="MIT",
  version="0.2.0",
  install_requires=[
    "loop_rate_limiters",
    "mink",
    "mujoco",
    "numpy",
    "scipy",
    "qpsolvers[proxqp]",
    "daqp",
    "rich",
    "tqdm",
    "opencv-python",
    "natsort",
    "psutil",
    "smplx @ git+https://github.com/vchoutas/smplx",
    "torch",
    "imageio[ffmpeg]",
    "trimesh>=4.0",
    "usd-core>=24.0",
    "coacd>=1.0.0",
  ],
  python_requires='>=3.10',
)
